[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py_lib"
version = "0.1.0"
description = "Generic engineering library"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "requests",
    "playwright"
]
